# Generated by Django 4.2.11 on 2024-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodels',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
